### ISSUE TITLE
Problem beim zurückschalten der EEP-Zeit

### ISSUE THREAD

**Issue by Damian-Rutkowski** [Andreas-Kreuz/ak-lua-bibliothek-fuer-eep#34]
Das Ampelsystem scheint sich aufzuhängen sobald die EEP-Zeit zurückgestellt wird.

**Comment by Andreas-Kreuz** [comment]
In dem Fall muss das Skript neu geladen werden, da die Schaltungen schauen, wieviel Zeit seit der letzten Schaltung vergangen ist.
