### ISSUE TITLE
Lua schreibt RAM voll

### ISSUE THREAD

**Issue by Damian-Rutkowski** [Andreas-Kreuz/ak-lua-bibliothek-fuer-eep#38]
Nach einiger Zeit im 3D Modus füllt sich mein RAM-Speicher voll. Das hat wohl mit der *.json-Datei zutun die für EEP-Web aktuell gehalten wird.

Kannst du das nachvollziehen?

**Comment by Andreas-Kreuz** [comment]
Für EEP kann ich das nicht bestätigen.
Allerdings frisst mein Browser eine Menge Speicher.
Starte mal den Task-Manager und sortiere nach Speicherauslastung.

**Comment by Andreas-Kreuz** [comment]
Konnte nur einmal beobachet werden.
