### ISSUE TITLE
Bedarfs/Anforderungsampeln

### ISSUE THREAD

**Issue by Damian-Rutkowski** [Andreas-Kreuz/ak-lua-bibliothek-fuer-eep#7]
Für Feuerwehr oder Fußgänger gibt es sogenannte Bedarfs/Anforderungsampeln, ist das bisher schon möglich wenn ich eine extrem lange Wartezeit für Fußgänger gebe und über eine Anforderung die Ampel erzwinge den Fußgängern grün zu geben?

Falls Unklarheiten bestehen, einfach fragen.

**Comment by Andreas-Kreuz** [comment]
Man könnte Fahrzeuge bestimmter Routen mit höherer Prio behandeln.

**Comment by Damian-Rutkowski** [comment]
Ich werde danach noch schauen, der Wunsch ist mal da, aber ich könnte mir vorstellen das sich das bereits über ein paar Tricks lösen lässt.

**Comment by Andreas-Kreuz** [comment]
Sollte mit den unterschiedlichen Zählweisen für Verkehr erledigt sein.
https://andreas-kreuz.github.io/ak-lua-bibliothek-fuer-eep/anleitungen-fortgeschrittene/tutorial3-priorisierung
