### ISSUE TITLE
Versionsnummer des Scripts direkt im Script einbauen und print() Ausgabe am Ende ausgeben das Erfolgreich eingebunden wurde

### ISSUE THREAD

**Issue by Damian-Rutkowski** [Andreas-Kreuz/ak-lua-bibliothek-fuer-eep#9]

**Comment by Damian-Rutkowski** [comment]
Das ist eine Kleinigkeit hat aber auch niedrige Priorität. Der Gedanke dahinter war, wie bei vielen anderen „Lua-Bibliotheken“ das die print()-Meldung innerhalb der „eingebundenen“ Datei am Ende ist.

Beispiel: [TaskMemorizer von Benny](http://emaps-eep.de/lua/taskmemorizer)

**Comment by Andreas-Kreuz** [comment]
In Version 0.5.0 wird nun beim Laden der Datei ausgegeben, dass sie geladen wird. Versionsnummern gibt es noch keine.
